### ISSUE TITLE
Start tracking codebase health metrics

### ISSUE THREAD

**Issue by jmduke** [buttondown-email/roadmap#250]
- [x] Number of Python dependencies
- [x] Number of JS dependencies
- [x] Python test suite duraation
- [x] JS test suite duration
- [ ] Final subscriber-facing bundle size
- [ ] Final internal app bundle size
- [x] Typescript errors
- [x] ESLint warnings
- [ ] Number of TODOs
- [x] Number of open 'bug' issues
- [ ] Code coverage
